import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Noto_Sans_Georgian } from 'next/font/google';
import './globals.css';
import SideBar from './components/sidebar';

const getRoboto = Noto_Sans_Georgian({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Booki',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${getRoboto.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
